#!/usr/bin/env python3
"""Byte-match cloud preview PNGs against ALL local stage 3-6 base sprites.

Extends match_objects.py to cover stages 4-6 too. Reuses .obj_cache/ from prior run.
Writes scripts/objects_map_full.json with stages 3,4,5,6 and stage 2 cracking.
"""
import hashlib, json, os, sys, urllib.request
from pathlib import Path

API = "https://api.pixellab.ai/v2"
KEY = os.environ.get("PIXELLAB_API_KEY") or "d4bf0d79-f310-44dd-ac13-b33dee5bfce7"
ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
CACHE = ROOT / "scripts" / ".obj_cache"
CACHE.mkdir(exist_ok=True)

# species_canonical -> {stage: local_name}
SPECIES = {
    "mochima": {3: "mochilet", 4: "mochinix",  5: "mochilord",  6: "mochiavatar"},
    "drakkin": {3: "drakling", 4: "drakwhelp", 5: "drakwarden", 6: "drakon"},
    "feliq":   {3: "felikit",  4: "felisprout",5: "felisaber",  6: "felimythos"},
    "aviorn":  {3: "pip",      4: "fledge",    5: "skylord",    6: "talonglyph"},
    "tidle":   {3: "sigil",    4: "acolyte",   5: "archmage",   6: "aeonmage"},
}
COLORS = ["red", "blue", "green", "purple", "gold"]


def call(path):
    req = urllib.request.Request(f"{API}{path}", headers={"Authorization": f"Bearer {KEY}"})
    with urllib.request.urlopen(req, timeout=120) as r:
        return json.loads(r.read())


def fetch(url, dst):
    if dst.exists():
        return dst.read_bytes()
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=60) as r:
        b = r.read()
    dst.write_bytes(b)
    return b


def sha(b):
    return hashlib.sha256(b).hexdigest()


def main():
    all_objs, offset, limit = [], 0, 50
    while True:
        r = call(f"/objects?limit={limit}&offset={offset}")
        all_objs.extend(r["objects"])
        if offset + limit >= r["total"]:
            break
        offset += limit
    print(f"# total cloud objects: {len(all_objs)}", file=sys.stderr)

    cloud_hashes = {}
    for i, o in enumerate(all_objs):
        if o.get("status") != "completed" or not o.get("preview_url"):
            continue
        dst = CACHE / f"{o['id']}.png"
        try:
            b = fetch(o["preview_url"], dst)
        except Exception as e:
            print(f"  fetch fail {o['id']}: {e}", file=sys.stderr)
            continue
        cloud_hashes.setdefault(sha(b), []).append(o)
        if i % 30 == 0:
            print(f"  fetched {i}/{len(all_objs)}", file=sys.stderr)

    out = {
        "_note": "object_id mapping recovered via byte-match. Generated by match_objects_full.py.",
        "species_label": {"mochima": "slime", "drakkin": "dragon", "feliq": "kitten", "aviorn": "bird", "tidle": "wizard"},
        "stage_local_name": {sp: stages for sp, stages in SPECIES.items()},
        "stage2_cracking": {},
        "stage3_hatchling": {},
        "stage4_juvenile":  {},
        "stage5_adult":     {},
        "stage6_ultimate":  {},
    }

    # Hatchling/juvenile/adult/ultimate
    for sp, stages in SPECIES.items():
        for stage_n, local in stages.items():
            stage_key = {3: "stage3_hatchling", 4: "stage4_juvenile", 5: "stage5_adult", 6: "stage6_ultimate"}[stage_n]
            out[stage_key].setdefault(sp, {})
            for col in COLORS:
                p = ASSETS / col / f"{local}.png"
                if not p.exists():
                    print(f"  ! local missing: {col}/{local}.png", file=sys.stderr)
                    continue
                h = sha(p.read_bytes())
                matches = cloud_hashes.get(h, [])
                if matches:
                    out[stage_key][sp][col] = matches[0]["id"]
                else:
                    print(f"  ! no cloud match: {col}/{local}.png  (hash {h[:12]})", file=sys.stderr)
                    out[stage_key][sp][col] = None

    # Cracking
    for col in COLORS:
        p = ASSETS / "cracking" / f"{col}.png"
        if not p.exists():
            continue
        h = sha(p.read_bytes())
        matches = cloud_hashes.get(h, [])
        out["stage2_cracking"][col] = matches[0]["id"] if matches else None

    dst = ROOT / "scripts" / "objects_map_full.json"
    dst.write_text(json.dumps(out, indent=2))
    print(f"# wrote {dst}", file=sys.stderr)

    # report
    print("\n# coverage:")
    for stage_key in ["stage2_cracking", "stage3_hatchling", "stage4_juvenile", "stage5_adult", "stage6_ultimate"]:
        section = out[stage_key]
        if isinstance(section, dict) and section and isinstance(next(iter(section.values()), None), dict):
            total = sum(len(v) for v in section.values())
            found = sum(1 for v in section.values() for x in v.values() if x)
        else:
            total = len(section)
            found = sum(1 for x in section.values() if x)
        print(f"  {stage_key}: {found}/{total}")


if __name__ == "__main__":
    main()
